[workspace]
resolver = "2"
members = [
    "crates/reciplexa-syntax",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kageokaraito/reciplexa"

[workspace.dependencies]
rowan = "0.16"
reciplexa-syntax = { path = "crates/reciplexa-syntax" }
