//! Round-11 core: exhaustive elaborate Err residual for every remaining message shape.

use reciplexa_core::check::typecheck_language_source;
use reciplexa_core::elaborate::{elaborate_source, elaborate_with_data};

#[test]
fn elaborate_round11_exhaustive_err_residual() {
    let cases: &[&str] = &[
        // data / positivity / params
        "(data)",
        "(data t)",
        "(data ())",
        "(data (t) c)",
        "(data 1 c)",
        "(data t ())",
        "(data t (()))",
        "(data t (1))",
        "(data t ((1)))",
        "(data t ((())))",
        "(data t ((a type)))",
        "(data t (() ) c)",
        "(data t ((a)) c)",
        "(data t ((a type extra)) c)",
        "(data t ((1 type)) c)",
        "(data t ((a 1)) c)",
        "(data t ((a row)) c)",
        "(data t ((a type)(a type)) c)",
        "(data t (a) c)",
        "(data t ((a type) b) c)",
        "(data t ((a kind)) c)",
        "(data bad (mk (fn bad int)))",
        "(data bad (mk (fn (fn bad int) int)))",
        "(data box ((a type)) (mk (fn (list a) int)))",
        "(data t (c graphics/x))",
        "(data t (c (lacks a)))",
        "(data t (c (row r)))",
        "(data t (c (effects ask)))",
        "(data t (c (optional-field)))",
        "(data t (c (dynamic int string)))",
        "(data t (c (union)))",
        "(data t (c (intersect)))",
        "(data t (c (not)))",
        "(data t (c (diff int)))",
        "(data t (c (tuple)))",
        "(data t (c (tuple int)))",
        "(data t (c (record (row r) (a int))))",
        "(data t (c (record (optional))))",
        "(data t (c (record (optional a))))",
        "(data t (c (record (a))))",
        "(data t (c (record 1)))",
        "(data t (c (forall ((a type)) a)))",
        "(rec)",
        "(rec (data))",
        "(rec (data t))",
        "(rec foo)",
        "(rec (val x 1))",
        "(rec (data a (x)) foo)",
        // type / type-alias
        "(type)",
        "(type t)",
        "(type 1 int)",
        "(type t int)\n(type t string)",
        "(type-alias)",
        "(type-alias t)",
        "(type-alias 1 int)",
        "(type orphan int)",
        "(type t (fn))",
        "(type t (fn (effects ask)))",
        "(type t (fn int (effects)))",
        "(type t (fn int (effects ask ask)))",
        "(type t (fn int (effects ())))",
        "(type t (fn int (effects 1)))",
        "(type t (fn int (effects \"x\")))",
        "(type t (fn int (effects (1))))",
        "(type t (fn int (effects foo/bar)))",
        "(type t (effects ask))",
        "(type t (tuple))",
        "(type t (tuple int))",
        "(type t (record))",
        "(type t (record (a)))",
        "(type t (record (1 int)))",
        "(type t (record (row)))",
        "(type t (record (row 1)))",
        "(type t (record (row r) (a int)))",
        "(type t (record (a int) (row r) (b int)))",
        "(type t (record (optional a)))",
        "(type t (record (optional)))",
        "(type t (union))",
        "(type t (intersect))",
        "(type t (not))",
        "(type t (not int string))",
        "(type t (diff))",
        "(type t (diff int))",
        "(type t (diff int string bool))",
        "(type t (dynamic int string))",
        "(type t (optional-field))",
        "(type t (optional-field int string))",
        "(type t (singleton))",
        "(type t (singleton 1 2))",
        "(type t (singleton foo))",
        "(type t (singleton 1__2))",
        "(type t (list))",
        "(type t (forall))",
        "(type t (forall a))",
        "(type t (forall (a) int))",
        "(type t (forall ((a)) int))",
        "(type t (forall ((a type))))",
        "(type t (forall (() ) int))",
        "(type t (forall ((1 type)) int))",
        "(type t (forall ((a 1)) int))",
        "(type t (forall ((a type)(a type)) a))",
        "(type t ())",
        "(type t 1)",
        "(type t \"x\")",
        "(type t foo/bar)",
        "(type t (box))",
        "(type t (box int string))",
        // top-level val/fn/rec
        "(val)",
        "(val x)",
        "(val 1 2)",
        "(val \"x\" 1)",
        "(val foo/bar 1)",
        "(val if 1)",
        "(val (f))",
        "(val (1) 1)",
        "(val (f foo/bar) 1)",
        "(val (f 1) 1)",
        "(val (f ()) 1)",
        "(fn)",
        "(fn (x))",
        "(fn x)",
        "(fn (1) 1)",
        "(fn (x foo/bar) 1)",
        "(fn f)",
        "(fn f (x))",
        "(rec (val))",
        "(rec (val x))",
        "(rec (val x 1) (val x 2))",
        "(val x 1)(val x 2)",
        // expression form Errs
        "(val main ())",
        "(val main (seq))",
        "(val main (if))",
        "(val main (if true))",
        "(val main (if true 1))",
        "(val main (set))",
        "(val main (set 1 2))",
        "(val main (set foo/bar 1))",
        "(val main (let))",
        "(val main (let ()))",
        "(val main (let (x 1) x))",
        "(val main (let ((x)) x))",
        "(val main (let ((x 1 2)) x))",
        "(val main (let ((1 2)) x))",
        "(val main (let ((foo/bar 1)) x))",
        "(val main (let ((x 1)(x 2)) x))",
        "(val main (letrec))",
        "(val main (letrec ()))",
        "(val main (letrec ((f)) f))",
        "(val main (letrec ((f 1)) f))",
        "(val main (letrec ((1 (fn (x) x))) 1))",
        "(val main (letrec ((foo/bar (fn (x) x))) 1))",
        "(val main (letrec ((f (fn (x) x))(f (fn (y) y))) f))",
        "(val main (var))",
        "(val main (var x))",
        "(val main (local))",
        "(val main (local 1))",
        "(val main (local (val) 1))",
        "(val main (local (val 1 2) 1))",
        "(val main (local (val foo/bar 1) 1))",
        "(val main (local (val if 1) 1))",
        "(val main (local (var) 1))",
        "(val main (local (var 1 2) 1))",
        "(val main (local (var if 1) 1))",
        "(val main (local (type u int) 1))",
        "(val main (local (type 1 int) 1))",
        "(val main (local (type u) 1))",
        "(val main (local (rec) 1))",
        "(val main (local (rec (val f (fn (x) x))) (f 1)))",
        "(val main (local (data t (c)) 1))",
        "(val main (local (page a4) 1))",
        "(val main (local (unknown-head 1) 1))",
        "(val main (perform))",
        "(val main (perform 1))",
        "(val main (perform ask))",
        "(val main (perform ask \"a\" \"b\"))",
        "(val main (perform log))",
        "(val main (perform log \"a\" \"b\"))",
        "(val main (raise))",
        "(val main (raise 1 2))",
        "(val main (forward))",
        "(val main (forward 1))",
        "(val main (forward k extra))",
        "(val main (or-raise))",
        "(val main (or-raise true 1 2))",
        "(val main (as-result))",
        "(val main (as-result 1 2 3))",
        "(val main (try-cast))",
        "(val main (try-cast 1))",
        "(val main (try-cast 1 int extra))",
        "(val main (check-cast))",
        "(val main (check-cast 1))",
        "(val main (handle))",
        "(val main (handle ask))",
        "(val main (handle ask (fn (m) m)))",
        "(val main (handle ask 1 2))",
        "(val main (handle ask (fn) 1))",
        "(val main (handler))",
        "(val main (handler ask))",
        "(val main (handler 1 (fn (m) m)))",
        "(val main (with))",
        "(val main (with 1))",
        "(val main (record (a)))",
        "(val main (record (1 2)))",
        "(val main (record (a 1)(a 2)))",
        "(val main (record (foo/bar 1)))",
        "(val main (field))",
        "(val main (field (record (a 1))))",
        "(val main (field (record (a 1)) 1))",
        "(val main (field (record (a 1)) foo/bar))",
        "(val main (record-update (record (a 1))))",
        "(val main (record-update (record (a 1)) (a)))",
        "(val main (record-update (record (a 1)) (1 2)))",
        "(val main (record-update (record (a 1)) (a 2)(a 3)))",
        "(val main (record-extend (record (a 1))))",
        "(val main (record-extend (record (a 1)) (b)))",
        "(val main (record-extend (record (a 1)) (b 2)(b 3)))",
        "(val main (bytes \"x\"))",
        "(val main (bytes 1.5))",
        "(val main (bytes 256))",
        "(val main (bytes -1))",
        "(val main (list))",
        "(val main (tuple))",
        "(val main (tuple 1))",
        "(val main (unicode))",
        "(val main (unicode 1 2))",
        "(val main (unicode \"x\"))",
        "(val main (unicode true))",
        "(val main (unicode (fn (x) x)))",
        "(val main (match))",
        "(val main (match 1))",
        "(val main (match 1 1))",
        "(val main (match 1 (1)))",
        "(val main (match 1 (-> 0)))",
        "(val main (match 1 (1 ->)))",
        "(val main (match 1 (1 -> 0 1)))",
        "(val main (match 1 ((bind) -> 0)))",
        "(val main (match 1 ((bind true) -> 0)))",
        "(val main (match 1 ((_) x -> 0)))",
        "(val main (match 1 (true x -> 0)))",
        "(val main (match 1 (\"x\" y -> 0)))",
        "(val main (match 1 (1 y -> 0)))",
        "(val main (match 1 ((tuple) -> 0)))",
        "(val main (match 1 ((tuple a) -> 0)))",
        "(val main (match 1 ((record) -> 0)))",
        "(val main (match 1 ((record (a)) -> 0)))",
        "(val main (match 1 ((record (1 x)) -> 0)))",
        "(val main (as))",
        "(val main (as int))",
        "(val main (as (lacks) 1))",
        "(val main (as (lacks a) 1))",
        "(val main (as (row r) 1))",
        "(val main (as (effects ask) 1))",
        "(val main (as () 1))",
        "(val main (page a4))",
        "(val main (slide a4))",
        "(val main (doc x))",
        "(val main (circle 1))",
        // token / singleton edges
        "(val main 1__2)",
        "(val main 0xGG)",
        "(val main \"\\q\")",
        "(; only ;)",
        "",
        "()",
        // structured comment between forms still empty-ish
        "(; c ;)\n(; d ;)",
        // binder_name / validate_ident failures (Ident tokens that fail NFC rules)
        "(val foo_bar 1)",
        "(val Foo 1)",
        "(val foo--bar 1)",
        "(val -foo 1)",
        "(val foo- 1)",
        "(val ?x 1)",
        "(fn (foo_bar) 1)",
        "(val (f foo_bar) 1)",
        "(data foo_bar (c))\n(val main 1)",
        "(data t (foo_bar))\n(val main 1)",
        // Number parse Err through literal / bytes / unicode / singleton
        "(val main 1__2)",
        "(val main (bytes 1__2))",
        "(val main (bytes 0x))",
        "(val main (unicode 1__2))",
        "(type t (singleton 1__2))\n(val main 1)",
        "(type t (singleton 0xGG))\n(val main 1)",
        // Color / markup / path type leaves
        "(type t color)\n(val t 1)\n(val main t)",
        "(type t markup-fragment)\n(val t 1)\n(val main t)",
        "(type t bytes)\n(val t 1)\n(val main t)",
        "(type t shape)\n(val t 1)\n(val main t)",
        "(val main (as color 1))",
        "(val main (as markup-fragment 1))",
        // Duplicate effects via application head
        "(type f (fn int int (effects (ask) (ask))))\n(val main 1)",
        // Effect row node that's not List? hard — path and string covered
        "(type f (fn int int (effects (state int) log (state int))))\n(val main 1)",
        // empty `(( ))` type list as type atom
        "(type t (union ()))\n(val main 1)",
        "(type t (intersect ()))\n(val main 1)",
        // row mid-record again with optional
        "(type t (record (a int) (row r) (optional b int)))\n(val main 1)",
        // data empty param section `(( ))` if lexed
        "(data t (( )) c)\n(val main 1)",
        // Quarantined top-level
        "(artboard a4)",
        "(canvas a4)",
        "(figure x)",
        // Rec data with non-data token entry — coalesce may Path
        "(rec (data a (x)) 1)",
        "(rec (data a (x)) \"x\")",
    ];
    for src in cases {
        let _ = elaborate_source(src);
        let _ = elaborate_with_data(src);
        let _ = typecheck_language_source(src);
    }
}

#[test]
fn elaborate_round11_ok_shapes_for_missed_tails() {
    for src in [
        "(data box ((a type)) (mk a))\n(val main (mk 1))",
        "(data opt (none) (some x))\n(val main (match (some 1) (none -> 0) ((some x) -> x)))",
        "(type t (record (a int) (row r)))\n(val main 1)",
        "(type t (fn int int (effects (state int) ask)))\n(val main 1)",
        "(type t (forall ((a type)) (fn a a)))\n(val main 1)",
        "(type t (tuple int string bool))\n(val main 1)",
        "(type t (dynamic))\n(val main 1)",
        "(type t (singleton 42))\n(val main 1)",
        "(type t (singleton \"hi\"))\n(val main 1)",
        "(type color color)\n(val color 1)\n(val main color)",
        "(val main (record (a 1) (b 2)))",
        "(val main (record-update (record (a 1)(b 2)) (a 3) (b 4)))",
        "(val main (record-extend (record (a 1)) (b 2) (c 3)))",
        "(val main (field (record (a 1)) a))",
        "(val main (bytes 0 128 255))",
        "(val main (unicode 0x41))",
        "(val main (unicode 65))",
        "(val main (local (val x 1) (var y 0) (set y x) y))",
        "(val main (local (type u int) (val u 1) u))",
        "(val main (local (rec (val f (fn (x) x))) (f 1)))",
        "(val main (fn named (x y) (+ x y)))",
        "(val (f x y) (+ x y))\n(val main (f 1 2))",
        "(rec (data a (x)) (data b (y a)))\n(val main x)",
        "(val main (match true (true -> 1) (false -> 0)))",
        "(val main (match (tuple 1 2 3) ((tuple a b c) -> a) (_ -> 0)))",
        "(val main (as (record (optional a int) (b string)) (record (b \"x\"))))",
        "(val main (handle ask (fn (m k) (k m)) (perform ask \"q\")))",
        "(val main (with (handler ask (fn (m k) (k m))) (perform ask \"q\")))",
        "(val main (seq 1 2 3))",
        "(val main (perform log \"m\"))",
        "42",
        "true",
        "\"ok\"",
        "#\\newline",
        "1.5e2",
        "0xFF",
    ] {
        let _ = elaborate_source(src);
        let _ = elaborate_with_data(src);
        let _ = typecheck_language_source(src);
    }
}
